### ISSUE TITLE
Question about list management

### ISSUE THREAD

**Issue by skipshean** [alexpgates/felix#2]
Hey Alex, I think I understand from your comments / documentation, but if I as admin want to remove a specific user from the recipient list, I have to do that manually in the MySQL DB, correct?

Thanks for clarifying.

**Comment by alexpgates** [comment]
@skipshean Correct. I just jump in and remove rows from the table if necessary. If you're on a Mac, I recommend [Sequel Pro](https://www.sequelpro.com/) to manage MySQL databases.
It really would be handy to have a way to manage everything completely through SMS, and have a way to permanently ban a specific number from joining / re-joining.

**Comment by skipshean** [comment]
Thanks for the quick reply -- it brought another question to mind.

Is _anyone_ in the recipient list able to send to the group?  In this use case, I wanted to have only a certain approved number(s) that could send to the group.

Is there a way to do that?

**Comment by alexpgates** [comment]
@skipshean Yes, anyone in the recipient list who texts the number will have their message delivered to the entire group.
There is no feature / option currently in place to limit who is able to send to the group, but it's definitely possible to do by updating the code to fit your needs.
